### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by johhnry** [Visor-Live/visor-builds#1]
Hi there,

Just saw recently Visor on talk.lurk and I tried to download it and run it (I am on debian Linux 4.19.0-kali1-amd64) , this is what I have : 

<pre><font color="#EF2929"><b>root@johk</b></font>:<font color="#729FCF"><b>~/Téléchargements/visor</b></font># ./Visor 
Segmentation fault</pre>

This is the output with valgrind (http://valgrind.org/) : 

<pre><font color="#EF2929"><b>root@johk</b></font>:<font color="#729FCF"><b>~/Téléchargements/visor</b></font># valgrind ./Visor 
==7925== Memcheck, a memory error detector
==7925== Copyright (C) 2002-2017, and GNU GPL&apos;d, by Julian Seward et al.
==7925== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==7925== Command: ./Visor
==7925== 
==7925== 
==7925== Process terminating with default action of signal 11 (SIGSEGV)
==7925==  Bad permissions for mapped region at address 0xA4E5B0
==7925==    at 0xA4E5B0: ??? (in /root/Téléchargements/visor/Visor)
==7925==    by 0x70F7661: node::http2::Http2Session::Callbacks::Callbacks(bool) (in /root/Téléchargements/visor/libnode.so)
==7925==    by 0x70F7724: ??? (in /root/Téléchargements/visor/libnode.so)
==7925==    by 0x583A399: call_init.part.0 (dl-init.c:72)
==7925==    by 0x583A495: call_init (dl-init.c:118)
==7925==    by 0x583A495: _dl_init (dl-init.c:119)
==7925==    by 0x582C0C9: ??? (in /usr/lib/x86_64-linux-gnu/ld-2.28.so)
==7925== 
==7925== HEAP SUMMARY:
==7925==     in use at exit: 136,031 bytes in 895 blocks
==7925==   total heap usage: 1,514 allocs, 619 frees, 229,371 bytes allocated
==7925== 
==7925== LEAK SUMMARY:
==7925==    definitely lost: 0 bytes in 0 blocks
==7925==    indirectly lost: 0 bytes in 0 blocks
==7925==      possibly lost: 1,352 bytes in 18 blocks
==7925==    still reachable: 134,679 bytes in 877 blocks
==7925==                       of which reachable via heuristic:
==7925==                         stdstring          : 34 bytes in 1 blocks
==7925==                         newarray           : 1,536 bytes in 16 blocks
==7925==         suppressed: 0 bytes in 0 blocks
==7925== Rerun with --leak-check=full to see details of leaked memory
==7925== 
==7925== For counts of detected and suppressed errors, rerun with: -v
==7925== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Erreur de segmentation</pre>

Thanks in advance

**Comment by EmperorJack** [comment]
Hi @johhnry,

Thanks for trying Visor and reporting the error. I've just released a new version of Visor that may resolve your issue. I'm thinking this issue was caused as Visor was previously using an older version of electron that crashes on debian. The new version now uses a more recent version of electron. I've had it tested on debian stretch.

You can find the latest builds here: https://github.com/Visor-Live/visor-builds/releases

Let me know how you go!

**Comment by johhnry** [comment]
Hello @EmperorJack, 

Thanks for your reply, I downloaded the latest version of Visor and it's working well !
I let you know if I have other problems.

Thanks again

**Comment by johhnry** [comment]
Hello @EmperorJack, 

Thanks for your reply, I downloaded the latest version of Visor and it's working well !
I let you know if I have other problems.

Thanks again
