### ISSUE TITLE
'Create layer/codetap with the same name' options sometimes doesn't work

### ISSUE THREAD

**Issue by Real-John-Cheung** [Visor-Live/visor-builds#10]
Thanks for the amazing app!

it seems that this check box sometimes doesn't works as expected (no layer/codetap with the same name is created)
<img width="423" alt="螢幕截圖 2021-04-16 下午5 31 14" src="https://user-images.githubusercontent.com/61215358/115004602-8caa6080-9ed9-11eb-8c0c-ba6660baa605.png">
On 2018 MacBookPro macOS Catalina 
hope that help your process

**Comment by EmperorJack** [comment]
Hey @Real-John-Cheung, thanks for your message!

I think I've replicated the issue - it looks like the interface won't display any new layers that are created while the sketch is not running. Though it looks like they will appear once you hit the run sketch button. Anyhow, I'll look into it 👾

**Comment by EmperorJack** [comment]
This should now be fixed in the latest 0.9.0 release 🏁
