### ISSUE TITLE
Naming global variables with processing function names overrides the function

### ISSUE THREAD

**Issue by julesvirallinen** [Visor-Live/visor-builds#14]
Hey, this is something I sometimes stumble on, not sure if it's a real issue, as it's easily avoidable when conscious of it. 

Anyway: if I create a global variable with the same name as a processing function, it overrides the function until sketch reset. Not sure if this needs to be addressed, just thought to note this! 

![image](https://user-images.githubusercontent.com/4622905/140545738-a7398278-03ac-45b7-9275-16afc681bac6.png)

![image](https://user-images.githubusercontent.com/4622905/140545749-5def8ae3-0599-4489-95b0-7ab4a101db61.png)

**Comment by julesvirallinen** [comment]
@rect is a bad example, but some that have caused confusion when I was learning to Visor were @width, or @clear (as boolean) etc.

**Comment by julesvirallinen** [comment]
PS: Bonus question (sorry for the ticket creeping), but have you had success using processing plugins?

**Comment by monkstone** [comment]
> Hey, this is something I sometimes stumble on, not sure if it's a real issue, as it's easily avoidable when conscious of it.
> 
> Anyway: if I create a global variable with the same name as a processing function, it overrides the function until sketch reset. Not sure if this needs to be addressed, just thought to note this!
> 
> ![image](https://user-images.githubusercontent.com/4622905/140545738-a7398278-03ac-45b7-9275-16afc681bac6.png)
> 
> ![image](https://user-images.githubusercontent.com/4622905/140545749-5def8ae3-0599-4489-95b0-7ab4a101db61.png)

This behaviour is expected with JRuby, what you are doing essentially is redefining `rect` in ruby (and the ruby method thereafter is called instead of java `rect`). Now sometimes you may want to legitimately call a java method when it has been redefined in ruby then you should create an alias:-
```ruby
alias :jrect :rect

attr_reader :rect
def settings
  size 300, 300
end

def setup
  sketch_title 'Rect'
  @rect = 100
end

def draw
  jrect 0, 0, 100, 100
end
  
```
Above code is a [JRubyArt](https://ruby-processing.github.io/JRubyArt/) sketch (currently I'm not using Visor)

**Comment by julesvirallinen** [comment]
Thanks for the alias trick! I'm not that familiar with the inner workings of Ruby, so I was wondering if this is something that could be avoided in Visor. 

I made this ticket mostly so that it could be mentioned in the docs, if this is intrinsic for ruby. This is a non-issue for me atm, but could be confusing for other visor-noobs.
