### ISSUE TITLE
Fatal Error on First Load: 

### ISSUE THREAD

**Issue by LulzRose** [Visor-Live/visor-builds#17]
Trying to run Visor for the first time and getting stuck on this error. I have tried multiple versions of java, Windows 10 Installation

LoadError: no such file to load -- bundler/shared_helpers
  require at org/jruby/RubyKernel.java:976
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59
   <main> at uri:classloader:/META-INF/init.rb:21
  require at org/jruby/RubyKernel.java:976
   (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
   <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59

ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- bundler/shared_helpers

**Comment by EmperorJack** [comment]
Thanks for reporting this. It may be fixed in the new version of Visor (0.11.0), which updates JRuby. Closing for now, can reopen if needed.
