### ISSUE TITLE
What is the Visor license?

### ISSUE THREAD

**Issue by MoiRouhs** [Visor-Live/visor-builds#3]
I don't the source code. Visor is an open source or free software?

**Comment by EmperorJack** [comment]
Hi @MoiRouhs. Visor is currently free to use and closed source. Though, I am planning to work towards an open source solution.

**Comment by jeremydouglass** [comment]
There is, however, a huge list of open software included in Visor -- JRuby, Processing, et cetera -- and many of those open licenses must be communicated to end users.

If you download Visor, launch the app, and click the License tab then it contains what looks like a comprehensive list.
