### ISSUE TITLE
Is SoundFlower still required?

### ISSUE THREAD

**Issue by aduncan** [Visor-Live/visor-builds#7]
Is SoundFlower still required, or can I just select, for e..g., Built-in Output from the list of Audio Input Devices?

**Comment by EmperorJack** [comment]
Hey @aduncan I think this is a bug where output devices are listed as well as input devices when selecting an audio device. So you will still need SoundFlower or another 3rd party app to handle your audio output->input routing. Thank you for raising the issue, I'll put it on my backlog.

On a side note, I've discovered some alternatives to SoundFlower if you need. These are [BlackHole](https://github.com/ExistentialAudio/BlackHole) and [iShowU Audio Capture](https://support.shinywhitebox.com/hc/en-us/articles/204161459-Installing-iShowU-Audio-Capture-Mojave-and-earlier-).
