### ISSUE TITLE
How can I switch to P2D mode? 

### ISSUE THREAD

**Issue by hokster7** [Visor-Live/visor-builds#8]
The following code does nothing:
```
  strokeCap ROUND
  strokeJoin ROUND
```

This is because `ROUND` is not supported under P3D mode, which Visor clearly uses.
How can I switch to P2D, so that my 2D rendering can benefit from round corners? =]

p.s. Sweet project! I found using Visor for rapid prototyping Processing super useful. Cmd+Enter to update is pretty sweet.

**Comment by EmperorJack** [comment]
Hey @fatuhoku, no worries, you can utilise P2D and other Processing modes through `PGraphics`. Check out my examples below 🙂 

```
@canvas = create_graphics width, height, P2D

def draw
  clear
  
  @canvas.begin_draw
  
  @canvas.background 255
  @canvas.stroke 0
  @canvas.stroke_weight 10
  @canvas.no_fill
  
  @canvas.stroke_cap ROUND
  @canvas.stroke_join ROUND
  
  @canvas.begin_shape
  @canvas.vertex 35, 20
  @canvas.vertex 65, 50
  @canvas.vertex 35, 80
  @canvas.end_shape
  
  @canvas.end_draw
  
  image @canvas, 0, 0
end
```

Or alternatively, with Visor's `with_graphics` helper:

```
@canvas = create_graphics width, height, P2D

def draw
  clear
  
  with_graphics @canvas do
    background 255
    stroke 0
    stroke_weight 10
    no_fill
    
    stroke_cap ROUND
    stroke_join ROUND
    
    begin_shape
    vertex 35, 20
    vertex 65, 50
    vertex 35, 80
    end_shape
  end
  
  image @canvas, 0, 0
end
```

Hopefully, that is sufficient enough. There is no way to make P2D the default mode at this time.

I'm glad you've been enjoying Visor, let me know if you have any feedback or further questions, cheers!
