### ISSUE TITLE
Feature request: using more MIDI controllers simultaneously with different channels 

### ISSUE THREAD

**Issue by mocmichal** [Visor-Live/visor-builds#9]
Would be nice if Visor would enable using more MIDI controllers simultaneously, each with its own channel.
Thanks for great piece of software.

**Comment by EmperorJack** [comment]
Hey @mocmichal, thanks for your feedback. You should be able to configure multiple MIDI input devices, each on one specific channel. Is this not possible for you? If you could elaborate further on what kind of setup you're going for and if you're running into any specific issues then that'd be awesome.

I think a known limitation at the moment is that you cannot use multiple channels for one MIDI input device. You also may need to restart Visor for it to pick up new devices!

**Comment by mocmichal** [comment]
I think it is enough for us for this time! Thanks, I didn't notice, that you can have multiple MIDI controllers.
